version: '2'
services:
  pgbadger:
    # image: laurentrichard/pgbadger
    build: .
    command: /var/log/postgresql/postgresql-*
    container_name: pgbadger
    environment:
      PGBADGER_DATA: "/data"
      AWS_ACCESS_KEY: ""
      AWS_SECRET_KEY: ""
      AWS_S3_REGION: "eu-west-1"
      AWS_S3_BUCKET: "pgbadger/www"
      CRON: 1
      CRON_PATTERN: "* * * * *"
    volumes:
      - "./pg_log:/var/log/postgresql"
      - "./data:/data"